config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'pages/courses'

  get 'pages/hired'

  get 'pages/alumni'

  get 'pages/faq'

  get 'pages/news'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def courses
  end

  def hired
  end

  def alumni
  end

  def faq
  end

  def news
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<br><br><br><br><br><br>

app/views/layouts/_header.html.erb
 <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
           <li><%= link_to "Metis", root_path, class:"navbar-brand" %></li>
        
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
          
        <li><%= link_to "Courses", pages_courses_path%></li>
        <li><%= link_to "Get Hired", pages_hired_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Alumni<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Data Science", pages_alumni_path %></li>
            <li><a href="#">Data Science</a></li>
            <li><a href="#">Ruby on Rails</a></li>
            <li><a href="#">UX & Fed</a></li>

          </ul>
        </li>
        <li><%= link_to "Faq", pages_faq_path %></li>
        <li><%= link_to "News", pages_news_path %></li> 
            <li><%= button_to "Contact", root_path, method: :get,class:"btn btn-primary sp"%></li>
            <li></li>
            <li><%= button_to "Apply", root_path, method: :get, class:"btn btn-primary sp" %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">   
           
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bootcamp</title>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render "layouts/footer" %>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
  <script src="js/bootstrap.min.js"></script>
</body>
</html>

app/views/pages/alumni.html.erb
<div class="alumni">
  <div class="container">
    <br><br><br><br><br><br><br>
    <h2>DATA SCIENCE ALUMNI</h2>
    <p>Over the course of twelve weeks, the men and women below completed the Metis Data Science Bootcamp, designed and taught by Datascope. Bootcamp students complete five data science projects of increasing independence and scope that iterate over the full question-to-answer process of practical data science.</p>

<p>Below each student's picture is a set of links to the student's portfolio. Each icon corresponds to one of the five in-class projects that the student has completed.</p>
    
    
    <h3>COHORT ONE: DECEMBER 2014</h3>
  
    <div class="row">
      <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
      <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
       <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
       <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
    </div><!-------row---->
    
    <br>
    <div class="row">
      <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
      <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
       <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
       <div class="col-md-3">
        <div class="inner">
          <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" >
          <h3>ALEX BLOCK</h3>
          <p>Growing up surrounded by lawyers, Alex learned that if you want answers, you need to ask the right questions. He maintains this same inquisitive nature when attacking data problems, always searching for unique approaches that lead to valuable insights. Alex is currently analyzing NBA ticket prices to try to identify and track rivalries between teams.</p><br>
          <div class="row text-center">
            <a hrref="#"><i class="fa fa-linkedin-square fa-3x"></i></a>  <a hrref="#"><i class="fa fa-github fa-3x"></i></a>
          </div>
        </div>
      </div><!-------colmd3---->
      
    </div><!-------row---->
    
  </div><!-------alumni---->
</div><!-------container-->

app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

app/views/pages/hired.html.erb
<h1>Pages#hired</h1>
<p>Find me in app/views/pages/hired.html.erb</p>

app/views/pages/home.html.erb
<body class="landing">
<div class="home">
  <div class="container "><br><br><br><br><br><br>
     <div class="head" >
        <div class="center logo"><%= image_tag("logo.png") %></div>
       <br><br>
        <h1>Data Science Bootcamps</h1>
        <h2>WHAT DOES METIS DO?</h2>

        <p>Metis accelerates your career in data science. Our immersive courses, designed by world-class industry practitioners, provide you with intensive, on-site instruction, access to an extensive network of speakers and mentors, and ongoing career coaching and job placement support. 
          Our goal is to prepare you to succeed as a data scientist.</p>

        <p><i> – Welcome to Metis. <br> <br> <%= link_to "LEARN MORE", root_path , class:"btn btn-lg btn-danger" %></i></p>

      <br><br><br><br>
   </div>
  </div>  
    <div class="succeed">
            <h2>OUR COMMITMENT</h2>
            <p>To help you succeed, we commit to:</p>
            <ul>
                <li><strong>Train you to think and act like a data scientist</strong>, which starts with asking the right questions and constantly adapting as new information is learned.</li>

                <li><strong>Teach you the most essential skills and technologies</strong> to establish a baseline knowledge from which you can springboard into your next job.</li>

                <li><strong>Immerse you in real-world, complex problems</strong> that you will unravel to create a robust portfolio of projects.</li>

                <li><strong>Create opportunities to connect with prospective employers</strong> and present to them your skills and passion.</li>

                <li><strong>Provide you with excellent student support</strong> so that your attention remains exclusively focused on becoming a data scientist.</li>

                <li><strong>Inject continual fun, passion, and excitement</strong> into your experience at Metis.</li>
            </ul>
      <br>
            <h2> OUR PHILOSOPHY </h2>

                <p>We strive, we sweat, we swear.<br>
                We go the extra mile.<br>
                We stage, we fail.<br>
                We try again. Get it right.<br>
                We learn. Connect. Come together.<br>
                <strong> Welcome to Metis.</strong> </p>
      <br>
            <h2> OUR Team </h2>
            <div class="container">
              <div class="row">
                
                <div class="col-md-2">
                  <div class="wrapper">
                      <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424988559/bo_hdowai.jpg"  data-toggle="modal" data-target="#myModal"  >
                    <h3>Bo Peng</h3>
                    <p>Instructor</p>
                  </div>
                </div>
              
              <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg"  data-toggle="modal" data-target="#myModal"  >
                    
                    <h3>Emily Smith</h3>
                    <p>Professionals</p>
                  </div>
                </div>
              
                <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989837/jas_pc5c3y.jpg"  data-toggle="modal" data-target="#myModal"  >
                    
                    <h3>Joe Smith</h3>
                    <p>Chief Executive Officer</p>
                  </div>
                </div>
                
                 <div class="col-md-2">
                  <div class="wrapper">
                     <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989976/instructors_laura_kyu1mp.jpg"  data-toggle="modal" data-target="#myModal"  >
                  
                    <h3>Brenda White</h3>
                    <p>Proffesional Person</p>
                  </div>
                </div>
                
                 <div class="col-md-2">
                  <div class="wrapper">
                     <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989974/instructors_lillian_aygner.jpg"  data-toggle="modal" data-target="#myModal"  >
                   
                    <h3>Le-A Knowles</h3>
                    <p>Fashionista</p>
                  </div>
                </div>
                
            </div>

     </div>
      <br><br>
       <div class="container">
              <div class="row">
                
                <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424988559/bo_hdowai.jpg"  data-toggle="modal" data-target="#myModal"  >
                  
                    <h3>Bo Peng</h3>
                    <p>Instructor</p>
                  </div>
                </div>
              
              <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989839/tar_kehltm.jpg"  data-toggle="modal" data-target="#myModal"  >
                  
                    <h3>Jerome Brown</h3>
                    <p>Rapper</p>
                  </div>
                </div>
              
                <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg"  data-toggle="modal" data-target="#myModal"  >
                    
                    <h3>Susan Garvey</h3>
                    <p>Head of Starbucks</p>
                  </div>
                </div>
                
                 <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989837/jas_pc5c3y.jpg"  data-toggle="modal" data-target="#myModal"  >
                  
                    <h3>Will Williams</h3>
                    <p>Boy band Singer</p>
                  </div>
                </div>
                
                 <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989974/instructors_lillian_aygner.jpg"  data-toggle="modal" data-target="#myModal"  >
                   
                    <h3>Berta Wafer</h3>
                    <p>Chief Financial Officer</p>
                  </div>
                </div>
                
            </div><!-----row---->             
     </div><!-----container---->

      
       <h2> OUR Advisors</h2>
            <div class="container">
              <div class="row">
                
                <div class="col-md-2">
                  <div class="wrapper" >
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424988559/bo_hdowai.jpg"  data-toggle="modal" data-target="#myModal"  > 
                    <h3>Bo Peng</h3>
                    <p>Instructor at <br> <strong>Trap House</strong></p>
                  </div>
                </div>
              
              <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989836/lau_uotqru.jpg" data-toggle="modal" data-target="#myModal"  > 
                
                    <h3>Emily Smith</h3>
                    <p>Professionals at <br><strong>Trap House</strong></p>
                  </div>
                </div>
              
                <div class="col-md-2">
                  <div class="wrapper">
                     <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989837/jas_pc5c3y.jpg" data-toggle="modal" data-target="#myModal"  >
                    
                    <h3>Joe Smith</h3>
                    <p>Chief Executive Officer at <br><strong>Trap House</strong></p>
                  </div>
                </div>
                
                 <div class="col-md-2">
                  <div class="wrapper">
                    <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989976/instructors_laura_kyu1mp.jpg" data-toggle="modal" data-target="#myModal"  >
                   
                    <h3>Brenda White</h3>
                    <p>Proffesional Person at <br><strong>Trap House</strong> </p>
                  </div>
                </div>
                
                
            </div><!-----row---->

     </div><!----containner-->
      <br><br>
      
</div>
  
   <div class="contact-form">
        <div class="form-container">
          <h2> Contact Form </h2>
          
            <input type="text" class="form-control" placeholder="Hello my name is [enter name here] and I'm interested in learning more about the Data Science Bootcamp"> <br>
            <input type="text" class="form-control" placeholder="Please follow up at [enter email address here]"> <br><br>
            <a class="btn btn-lg btn-primary">Submit</a> 
         
        </div>
      </div>
      <br><br><br><br>
  

<!-- Modal -->
<div class="modal" id="myModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
             <div class="wrapper"> 
               <img  src="http://res.cloudinary.com/bisonshare/image/upload/v1424989976/instructors_laura_kyu1mp.jpg" > 
               <h1>Laura Montemayor</h1>
               <p>Laura, a developer bootcamp graduate, is passionate about bringing people into technology and making things happen.</p>
        </div>

      </div>
      <div class="modal-body">
      </div>
    
    </div>
  </div>
</div>

app/views/pages/news.html.erb
<h1>Pages#news</h1>
<p>Find me in app/views/pages/news.html.erb</p>